name: Build / Test / Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install requirements
        run: npm install
      - name: Run Back-End
        run: npm run start-be &
      - name: Wait for Back-End to start
        run: sleep 10
      - name: Run Front-End
        run: npm run start-fe &
      - name: Wait for Front-End to start
        run: sleep 10
  
  ui-tests:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare prerequisites
        run: |
          npm install
          npm run start-be &
          sleep 10
          npm run start-fe &
          sleep 10
          npx playwright install
          sleep 10
      - name: Execute UI testst
        run: npm run test-ui

  deploy-production:
    needs: ui-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-lastest

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API }}
          wait-for-success: true